#!/bin/sh

set -e

case "$1" in
    configure)
        if [ -f '/etc/apache2/#enable_authz_svn#' ]; then
            # Enable on upgrades where this used to be implied by dav_svn.load
            if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
                . /usr/share/apache2/apache2-maintscript-helper
                apache2_invoke enmod authz_svn
                rm -f '/etc/apache2/#enable_authz_svn#'
            fi
        fi
        ;;
esac

#DEBHELPER#
